spring.datasource.url=jdbc:mysql://localhost:3306/hcms
spring.datasource.username=root
spring.datasource.password=naveen_rwt007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.ssl.enabled=true